[tool.poetry]
name = "feature_registry"
version = "0.1.0"
description = "https://github.com/pandov/ods-feature-registry"
authors = ["Viacheslav Pandov <pandovvd@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "1.26.4"
polars = "1.9.0"
polars-u64-idx = "1.12.0"
pyarrow = "17.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
